name: Run Checks

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  FORCE_COLOR: 1

jobs:
  uv-example:
    name: Run checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: wntrblm/nox@main

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install

      - name: Lint
        run: nox -s lint

      - name: Check Formatting
        run: nox -s check_format
